name: php
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      with:
        ref: main
        ssh-key: ${{secrets.SERVER_SSH_KEY}}
      - name: enter directory
        run: cd C:\Users\Administrator\php

    # env:
    #   host: ${{secrets.REMOTE_HOST}}
    #   username: ${{secrets.REMOTE_USER}}
    #   key: ${{secrets.SERVER_SSH_KEY}}
    #   passphrase: ${{ secrets.PASSPHRASE }}
    #   port: ${{secrets.REMOTE_PORT}}
    #   source: "src/"
    #   target: ${{secrets.REMOTE_TARGET}}
