name: php
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
      uses: actions/checkout@v3

      - name: deploy
      uses: actions/ssh-deploy@main
      
      env:
        SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
        SOURCE: "src/"
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_PORT: ${{secrets.REMOTE_PORT}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        REMOTE_TARGET: ${{secrets.REMOTE_TARGET}}
        