name: php
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: copy file via ssh password
        run: cd C:\Users\Administrator\php && git pull
        # uses: appleboy/scp-action@master
    env:
      host: ${{secrets.REMOTE_HOST}}
      username: ${{secrets.REMOTE_USER}}
      key: ${{secrets.SERVER_SSH_KEY}}
      passphrase: ${{ secrets.PASSPHRASE }}
      port: ${{secrets.REMOTE_PORT}}
      source: "src/"
      target: ${{secrets.REMOTE_TARGET}}
